BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[BATCH_DATA] (
    [ID] INT NOT NULL IDENTITY(1,1),
    [WTDose] FLOAT(53) NOT NULL,
    [CLDose] FLOAT(53) NOT NULL,
    [TimeStamp] DATETIME2 NOT NULL,
    CONSTRAINT [BATCH_DATA_pkey] PRIMARY KEY CLUSTERED ([ID])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
